### PR TITLE
Add an option to only print current projects

### PR DESCRIPTION
**Pull request by samoylovfp**
First of all thanks for the great tool!

I use oh-my-zsh with a bunch of plugins and I think this will be very nice to see the current running project without having to type `bartib current`. This helps with remembering that I need to switch projects.

### CODE REVIEW

**Comment by samoylovfp** [comment]
How I managed to set it up for my terminal
image

**Comment by nikolassv** [comment]
Thank you for your pull request. I moved the new option to the subcommand `projects`. I thought it may be a better fit there. 

The output for `projects` is a little different as it adds quotation marks and a newline. Would this work for you, too?

**Comment by samoylovfp** [comment]
I managed to make it working with some post-processing but this looks slightly worse

Function to generate the prompt value
image

How it looks
image

I'm OK with this if it makes more sense to you, you're the boss :smile:

**Comment by nikolassv** [comment]
You're right the trailing comma does not look good. You should be able to get rid of it with `paste` instead of  `tr`. Try this:

```bash
bartib projects -c | tr -d '\"' | paste -sd ',' -
```

**Comment by samoylovfp** [comment]
Yes it now looks great! Thanks again for this project and your help!

**Pull request merged**
